import { Listing, Reservation, User } from '@/types';

const now = new Date();
const h = (n: number) => new Date(now.getTime() + n * 3600000).toISOString();

const APPROVED = 'approved' as const;

export const DEMO_USERS: User[] = [
  {
    id: 'demo1',
    email: 'demo@nibblen.com',
    name: 'Demo User',
    role: 'consumer',
    // Demo starts in consumer mode by default.
    // Provider mode is available via the mode switcher (providerStatus is approved).
    currentMode: 'consumer',
    canProvide: true,
    city: 'San Francisco',
    zipCode: '94105',
    bio: 'Exploring NibbleNet — a network for sharing extra food.',
    providerStatus: APPROVED,
    providerType: 'Restaurant',
    businessName: 'Demo Kitchen',
    integrityPolicyAccepted: true,
    foodSafetyAccepted: true,
    waiverSigned: true,
  },
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'l1',
    providerId: 'provider1',
    providerName: 'Maria Chen',
    businessName: 'Golden Garden Restaurant',
    businessType: 'Restaurant',
    title: 'Mixed Dim Sum Bundle (10 pcs)',
    description:
      'Freshly steamed har gow, siu mai, and char siu bao — made this morning and ready to go. Perfect for a quick lunch or afternoon snack. Served in a takeout box.',
    category: 'Meals',
    tags: ['Chinese'],
    allergens: ['shellfish', 'gluten', 'soy', 'eggs'],
    price: 8,
    originalPrice: 22,
    quantity: 5,
    quantityReserved: 2,
    status: 'available',
    pickupAddress: '480 Brannan St',
    pickupCity: 'San Francisco',
    pickupZip: '94107',
    pickupLat: 37.7767,
    pickupLng: -122.3968,
    pickupStartTime: '13:00',
    pickupEndTime: '15:00',
    pickupInstructions: 'Come to the side entrance on Brannan St. Tell the host you have a NibbleNet pickup. Ask for Maria.',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&q=80',
    createdAt: h(-2),
    expiresAt: h(3),
    distance: 0.4,
  },
  {
    id: 'l2',
    providerId: 'provider2',
    providerName: 'James Ortega',
    businessName: 'Sunrise Bakery',
    businessType: 'Bakery',
    title: 'Assorted Morning Pastry Box',
    description:
      'A mix of today\'s leftover pastries: croissants, pain au chocolat, almond danishes, and cinnamon rolls. All baked fresh this morning — grab them before they\'re gone!',
    category: 'Baked Goods',
    tags: ['Western'],
    allergens: ['gluten', 'dairy', 'eggs', 'tree-nuts'],
    price: 6,
    originalPrice: 18,
    quantity: 8,
    quantityReserved: 3,
    status: 'available',
    pickupAddress: '3251 20th Ave',
    pickupCity: 'San Francisco',
    pickupZip: '94132',
    pickupLat: 37.7264,
    pickupLng: -122.4779,
    pickupStartTime: '14:00',
    pickupEndTime: '17:00',
    pickupInstructions: 'Walk to the front counter and mention NibbleNet. Your box will be pre-packed and ready.',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80',
    createdAt: h(-3),
    expiresAt: h(4),
    distance: 1.2,
  },
  {
    id: 'l3',
    providerId: 'provider3',
    providerName: 'Priya Sharma',
    businessName: 'Fresh & Local Market',
    businessType: 'Grocery',
    title: 'Seasonal Fruit Bag (2 lbs)',
    description:
      'A hand-picked mix of perfectly ripe seasonal fruits — strawberries, oranges, apples, and kiwi. Too ripe to sit on shelves, but perfect to eat today or tomorrow!',
    category: 'Fruits',
    tags: [],
    allergens: [],
    price: 4,
    originalPrice: 12,
    quantity: 10,
    quantityReserved: 1,
    status: 'available',
    pickupAddress: '198 Potrero Ave',
    pickupCity: 'San Francisco',
    pickupZip: '94103',
    pickupLat: 37.7695,
    pickupLng: -122.4086,
    pickupStartTime: '16:00',
    pickupEndTime: '18:30',
    pickupInstructions: 'Head to the produce section near the entrance. Pre-bagged bags will be on the shelf labeled "NibbleNet."',
    imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600&q=80',
    createdAt: h(-1),
    expiresAt: h(5),
    distance: 0.9,
  },
  {
    id: 'l4',
    providerId: 'provider1',
    providerName: 'Maria Chen',
    businessName: 'Golden Garden Restaurant',
    businessType: 'Restaurant',
    title: 'Sushi Combo (12 pcs)',
    description:
      'Chef\'s choice sushi selection — salmon nigiri, tuna rolls, avocado rolls, and spicy crab. Made fresh this afternoon. Best consumed today.',
    category: 'Meals',
    tags: ['Japanese'],
    allergens: ['shellfish', 'soy', 'gluten'],
    price: 12,
    originalPrice: 32,
    quantity: 3,
    quantityReserved: 0,
    status: 'available',
    pickupAddress: '480 Brannan St',
    pickupCity: 'San Francisco',
    pickupZip: '94107',
    pickupLat: 37.7767,
    pickupLng: -122.3968,
    pickupStartTime: '17:30',
    pickupEndTime: '19:00',
    pickupInstructions: 'Use the main entrance. Pickup is at the host stand — they\'ll have a list of NibbleNet orders.',
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80',
    createdAt: h(-1),
    expiresAt: h(4),
    distance: 0.4,
  },
  {
    id: 'l5',
    providerId: 'provider3',
    providerName: 'Priya Sharma',
    businessName: 'Fresh & Local Market',
    businessType: 'Grocery',
    title: 'Mixed Greens & Veggie Pack',
    description:
      'Baby spinach, arugula, cherry tomatoes, and cucumber. Organic, locally sourced. Approaching best-by date but perfectly fresh for the next 2–3 days.',
    category: 'Vegetables',
    tags: [],
    allergens: [],
    price: 3,
    originalPrice: 9,
    quantity: 15,
    quantityReserved: 5,
    status: 'available',
    pickupAddress: '198 Potrero Ave',
    pickupCity: 'San Francisco',
    pickupZip: '94103',
    pickupLat: 37.7695,
    pickupLng: -122.4086,
    pickupStartTime: '15:00',
    pickupEndTime: '19:00',
    pickupInstructions: 'Bags are at the customer service desk. Show your reservation code.',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',
    createdAt: h(-2),
    expiresAt: h(6),
    distance: 0.9,
  },
  {
    id: 'l6',
    providerId: 'provider2',
    providerName: 'James Ortega',
    businessName: 'Sunrise Bakery',
    businessType: 'Bakery',
    title: 'Mini Muffin Variety Pack (6)',
    description:
      'Six mini muffins — blueberry, chocolate chip, and lemon poppyseed. Baked this morning, slightly past peak but still delicious. Great for a snack or lunchbox treat.',
    category: 'Baked Goods',
    tags: ['Western'],
    allergens: ['gluten', 'dairy', 'eggs'],
    price: 3,
    originalPrice: 9,
    quantity: 12,
    quantityReserved: 7,
    status: 'available',
    pickupAddress: '3251 20th Ave',
    pickupCity: 'San Francisco',
    pickupZip: '94132',
    pickupLat: 37.7264,
    pickupLng: -122.4779,
    pickupStartTime: '15:00',
    pickupEndTime: '18:00',
    pickupInstructions: 'Packaged boxes will be at the register with your name. Just show your confirmation code.',
    imageUrl: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=600&q=80',
    createdAt: h(-4),
    expiresAt: h(3),
    distance: 1.2,
  },
  {
    id: 'l7',
    providerId: 'provider1',
    providerName: 'Maria Chen',
    businessName: 'Golden Garden Restaurant',
    businessType: 'Restaurant',
    title: 'Green Tea Smoothie 3-Pack',
    description:
      'Matcha green tea smoothies blended with banana and oat milk. Made in-house. Three 12oz bottles. Best today.',
    category: 'Drinks',
    tags: ['Japanese'],
    allergens: [],
    price: 5,
    originalPrice: 15,
    quantity: 6,
    quantityReserved: 2,
    status: 'available',
    pickupAddress: '480 Brannan St',
    pickupCity: 'San Francisco',
    pickupZip: '94107',
    pickupLat: 37.7767,
    pickupLng: -122.3968,
    pickupStartTime: '12:00',
    pickupEndTime: '16:00',
    pickupInstructions: 'Grab from the refrigerator at the entrance counter. Show your code to the cashier.',
    imageUrl: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=600&q=80',
    createdAt: h(-1),
    expiresAt: h(5),
    distance: 0.4,
  },
  {
    id: 'l8',
    providerId: 'provider3',
    providerName: 'Priya Sharma',
    businessName: 'Fresh & Local Market',
    businessType: 'Grocery',
    title: 'Cheese & Charcuterie Ends',
    description:
      'End cuts and off-pieces from our cheese counter: aged cheddar, gouda, brie, and manchego. Also includes some salami and prosciutto ends. Great for a cheese board.',
    category: 'Dairy',
    tags: ['Mediterranean'],
    allergens: ['dairy'],
    price: 7,
    originalPrice: 22,
    quantity: 4,
    quantityReserved: 1,
    status: 'available',
    pickupAddress: '198 Potrero Ave',
    pickupCity: 'San Francisco',
    pickupZip: '94103',
    pickupLat: 37.7695,
    pickupLng: -122.4086,
    pickupStartTime: '14:00',
    pickupEndTime: '18:00',
    pickupInstructions: 'Ask at the deli counter for your NibbleNet order. Bring your code.',
    imageUrl: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&q=80',
    createdAt: h(-3),
    expiresAt: h(4),
    distance: 0.9,
  },
  {
    id: 'l9',
    providerId: 'provider1',
    providerName: 'Maria Chen',
    businessName: 'Golden Garden Restaurant',
    businessType: 'Restaurant',
    title: 'Chicken Tikka Masala Bowl',
    description:
      'Rich, creamy chicken tikka masala with basmati rice. Made fresh today from our lunch service. One generous portion. Best reheated if not eating immediately.',
    category: 'Meals',
    tags: ['Indian'],
    allergens: ['dairy'],
    price: 7,
    originalPrice: 18,
    quantity: 4,
    quantityReserved: 2,
    status: 'available',
    pickupAddress: '480 Brannan St',
    pickupCity: 'San Francisco',
    pickupZip: '94107',
    pickupLat: 37.7767,
    pickupLng: -122.3968,
    pickupStartTime: '18:00',
    pickupEndTime: '20:00',
    pickupInstructions: 'Pickup at the side door on Brannan St after 6pm. Knock and mention NibbleNet.',
    imageUrl: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=600&q=80',
    createdAt: h(-2),
    expiresAt: h(5),
    distance: 0.4,
  },
  {
    id: 'l10',
    providerId: 'provider2',
    providerName: 'James Ortega',
    businessName: 'Sunrise Bakery',
    businessType: 'Bakery',
    title: 'Sourdough Loaf (Day-Old)',
    description:
      'Yesterday\'s sourdough — still soft inside with a crispy crust. Our artisan loaves are baked in a stone hearth. Perfect for toast, sandwiches, or dipping in olive oil.',
    category: 'Baked Goods',
    tags: ['Western'],
    allergens: ['gluten'],
    price: 4,
    originalPrice: 11,
    quantity: 6,
    quantityReserved: 4,
    status: 'available',
    pickupAddress: '3251 20th Ave',
    pickupCity: 'San Francisco',
    pickupZip: '94132',
    pickupLat: 37.7264,
    pickupLng: -122.4779,
    pickupStartTime: '10:00',
    pickupEndTime: '14:00',
    pickupInstructions: 'Loaves are bagged and labeled at the front counter. Mention NibbleNet when you arrive.',
    imageUrl: 'https://images.unsplash.com/photo-1484723091739-30f299ad3074?w=600&q=80',
    createdAt: h(-5),
    expiresAt: h(2),
    distance: 1.2,
  },
  {
    id: 'l11',
    providerId: 'provider3',
    providerName: 'Priya Sharma',
    businessName: 'Fresh & Local Market',
    businessType: 'Grocery',
    title: 'Snack Mix Pantry Bundle',
    description:
      'Assorted pantry snacks nearing best-by date: trail mix, rice crackers, granola bars, and roasted nuts. All still fresh and delicious. Great variety pack.',
    category: 'Snacks',
    tags: [],
    allergens: ['peanuts', 'tree-nuts', 'gluten', 'soy'],
    price: 5,
    originalPrice: 16,
    quantity: 8,
    quantityReserved: 2,
    status: 'available',
    pickupAddress: '198 Potrero Ave',
    pickupCity: 'San Francisco',
    pickupZip: '94103',
    pickupLat: 37.7695,
    pickupLng: -122.4086,
    pickupStartTime: '11:00',
    pickupEndTime: '17:00',
    pickupInstructions: 'Bundles are in a crate near the checkout lanes. Grab one and show your code at the register.',
    imageUrl: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=600&q=80',
    createdAt: h(-1),
    expiresAt: h(6),
    distance: 0.9,
  },
  {
    id: 'l12',
    providerId: 'provider1',
    providerName: 'Maria Chen',
    businessName: 'Golden Garden Restaurant',
    businessType: 'Restaurant',
    title: 'Taco Box (6 pcs)',
    description:
      'Street-style tacos: 2 chicken tinga, 2 al pastor, 2 roasted veggie. Corn tortillas, fresh salsa, pickled onion, and lime. End of service extras — delicious!',
    category: 'Meals',
    tags: ['Mexican'],
    allergens: ['gluten'],
    price: 6,
    originalPrice: 16,
    quantity: 3,
    quantityReserved: 0,
    status: 'available',
    pickupAddress: '480 Brannan St',
    pickupCity: 'San Francisco',
    pickupZip: '94107',
    pickupLat: 37.7767,
    pickupLng: -122.3968,
    pickupStartTime: '20:00',
    pickupEndTime: '21:30',
    pickupInstructions: 'After 8pm, use the main entrance. Ask for the NibbleNet taco order.',
    imageUrl: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=600&q=80',
    createdAt: h(-1),
    expiresAt: h(6),
    distance: 0.4,
  },
  {
    id: 'l13',
    providerId: 'provider2',
    providerName: 'James Ortega',
    businessName: 'Sunrise Bakery',
    businessType: 'Bakery',
    title: 'Sunrise Rescue Bundle 🎁',
    description:
      "Mystery end-of-day box from Sunrise Bakery — could be pastries, loaves, muffins, or a mix of all three. You won't know exactly what's inside, but it's always worth it. Allergens are fully disclosed below for your safety.",
    category: 'Baked Goods',
    tags: ['Western'],
    allergens: ['gluten', 'dairy', 'eggs', 'tree-nuts'],
    price: 5,
    originalPrice: 20,
    quantity: 4,
    quantityReserved: 1,
    status: 'available',
    pickupAddress: '3251 20th Ave',
    pickupCity: 'San Francisco',
    pickupZip: '94132',
    pickupLat: 37.7264,
    pickupLng: -122.4779,
    pickupStartTime: '17:00',
    pickupEndTime: '19:00',
    pickupInstructions: 'Ask at the front counter for your Rescue Bundle. Your box will be sealed and ready.',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80',
    isRescueBundle: true,
    createdAt: h(-1),
    expiresAt: h(3),
    distance: 1.2,
  },
  {
    id: 'l14',
    providerId: 'provider1',
    providerName: 'Maria Chen',
    businessName: 'Golden Garden Restaurant',
    businessType: 'Restaurant',
    title: 'Mystery Meal Box',
    description:
      "A generous surprise selection from today's kitchen — could be any combination of our popular dishes. Always a great deal!",
    category: 'Meals',
    tags: ['Chinese', 'Japanese'],
    allergens: ['gluten', 'soy', 'shellfish'],
    price: 10,
    originalPrice: 28,
    quantity: 4,
    quantityReserved: 0,
    status: 'available',
    pickupAddress: '480 Brannan St',
    pickupCity: 'San Francisco',
    pickupZip: '94107',
    pickupLat: 37.7767,
    pickupLng: -122.3968,
    pickupStartTime: '18:00',
    pickupEndTime: '20:00',
    pickupInstructions: 'Pick up at the host stand. Mention NibbleNet Mystery Meal Box.',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&q=80',
    isSurpriseBox: true,
    surpriseBoxSize: 'medium',
    createdAt: h(-2),
    expiresAt: h(4),
    distance: 0.4,
  },
  {
    id: 'l15',
    providerId: 'provider3',
    providerName: 'Priya Sharma',
    businessName: 'Fresh & Local Market',
    businessType: 'Grocery',
    title: 'Surprise Grocery Haul',
    description:
      'A large surprise box packed with assorted groceries — fruits, vegetables, dairy, snacks, and more. Great variety, amazing value!',
    category: 'Fruits',
    tags: [],
    allergens: ['dairy', 'tree-nuts'],
    price: 18,
    originalPrice: 50,
    quantity: 3,
    quantityReserved: 0,
    status: 'available',
    pickupAddress: '198 Potrero Ave',
    pickupCity: 'San Francisco',
    pickupZip: '94103',
    pickupLat: 37.7695,
    pickupLng: -122.4086,
    pickupStartTime: '14:00',
    pickupEndTime: '18:00',
    pickupInstructions: 'Large boxes are at the customer service desk. Bring your code.',
    imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600&q=80',
    isSurpriseBox: true,
    surpriseBoxSize: 'large',
    createdAt: h(-1),
    expiresAt: h(6),
    distance: 0.9,
  },
];

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: 'r1',
    listingId: 'l2',
    listing: MOCK_LISTINGS[1],
    consumerId: 'demo1',
    consumerName: 'Demo User',
    quantity: 1,
    totalPrice: 6,
    status: 'confirmed',
    confirmationCode: 'NN-X7KP2M',
    createdAt: h(-1),
  },
  {
    id: 'r2',
    listingId: 'l5',
    listing: MOCK_LISTINGS[4],
    consumerId: 'demo1',
    consumerName: 'Demo User',
    quantity: 2,
    totalPrice: 6,
    status: 'picked_up',
    confirmationCode: 'NN-Q9RN4A',
    createdAt: h(-24),
  },
];
